# Generated by Django 6.0.6 on 2026-06-07 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='niveau',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='matiere',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matiere',
            name='volume_horaire',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
