# Generated by Django 6.0.6 on 2026-06-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('non_justifiee', 'Non justifiée'), ('justifiee', 'Justifiée')], default='non_justifiee', max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
